/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  price?: number;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gender?: "male" | "female";
  category?: "shirt" | "underwear" | "pants" | "shoes" | "accessories" | "other";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes = Product | SanityImageCrop | SanityImageHotspot | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/queries.ts
// Variable: PRODUCTS_QUERY
// Query: *[_type == "product"] {    _id,    _createdAt,    name,    price,    gender,    category,    "image": image.asset->url  }
export type PRODUCTS_QUERYResult = Array<{
  _id: string;
  _createdAt: string;
  name: string | null;
  price: number | null;
  gender: "female" | "male" | null;
  category: "accessories" | "other" | "pants" | "shirt" | "shoes" | "underwear" | null;
  image: string | null;
}>;
// Variable: PRODUCT_BY_ID_QUERY
// Query: *[_type == "product" && _id == $id][0] {    _id,    _createdAt,    name,    price,    gender,    category,    image {      asset-> {        _id,        url      },      hotspot    }  }
export type PRODUCT_BY_ID_QUERYResult = {
  _id: string;
  _createdAt: string;
  name: string | null;
  price: number | null;
  gender: "female" | "male" | null;
  category: "accessories" | "other" | "pants" | "shirt" | "shoes" | "underwear" | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
} | null;
// Variable: PRODUCTS_WITH_FULL_IMAGE_QUERY
// Query: *[_type == "product"] {    _id,    _createdAt,    name,    price,    gender,    category,    image {      asset-> {        _id,        url,        metadata {          lqip,          dimensions {            width,            height          }        }      },      hotspot,      crop    }  }
export type PRODUCTS_WITH_FULL_IMAGE_QUERYResult = Array<{
  _id: string;
  _createdAt: string;
  name: string | null;
  price: number | null;
  gender: "female" | "male" | null;
  category: "accessories" | "other" | "pants" | "shirt" | "shoes" | "underwear" | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"product\"] {\n    _id,\n    _createdAt,\n    name,\n    price,\n    gender,\n    category,\n    \"image\": image.asset->url\n  }\n": PRODUCTS_QUERYResult;
    "\n  *[_type == \"product\" && _id == $id][0] {\n    _id,\n    _createdAt,\n    name,\n    price,\n    gender,\n    category,\n    image {\n      asset-> {\n        _id,\n        url\n      },\n      hotspot\n    }\n  }\n": PRODUCT_BY_ID_QUERYResult;
    "\n  *[_type == \"product\"] {\n    _id,\n    _createdAt,\n    name,\n    price,\n    gender,\n    category,\n    image {\n      asset-> {\n        _id,\n        url,\n        metadata {\n          lqip,\n          dimensions {\n            width,\n            height\n          }\n        }\n      },\n      hotspot,\n      crop\n    }\n  }\n": PRODUCTS_WITH_FULL_IMAGE_QUERYResult;
  }
}
